-- MULTI AKCIÓK public offer-price history.
-- Loyalty-card identifiers are intentionally NOT stored here.

create table if not exists public.offer_snapshots (
  id bigint generated by default as identity primary key,
  observed_date date not null,
  offer_key text not null,
  store text not null,
  name text not null,
  category text not null,
  price integer not null check (price > 0),
  old_price integer,
  unit_label text not null,
  unit_price integer,
  valid_to date,
  condition_text text,
  source_url text,
  created_at timestamptz not null default now(),
  unique (observed_date, offer_key)
);

create index if not exists offer_snapshots_offer_key_date_idx
  on public.offer_snapshots (offer_key, observed_date desc);

alter table public.offer_snapshots enable row level security;

revoke all on table public.offer_snapshots from anon, authenticated;
grant select, insert, update on table public.offer_snapshots to service_role;
grant usage, select on sequence public.offer_snapshots_id_seq to service_role;
