-- MULTI AKCIÓK is stored inside the TELEKI Supabase project in an isolated schema.
-- Loyalty-card identifiers are intentionally NOT stored in Supabase.
--
-- Production objects:
--   multi_akciok.offer_snapshots
--   multi_akciok.refresh_state
--   public.multi_akciok_upsert_snapshots(jsonb)       service_role only
--   public.multi_akciok_try_begin_refresh(integer)    service_role only
--   public.multi_akciok_finish_refresh(text,int,text)  service_role only
--   public.multi_akciok_offer_history(text,integer)    read-only for anon/authenticated
--
-- Daily collection is executed by Supabase Edge Function "multi-akciok-snapshot"
-- through Supabase Cron at 04:17 UTC.
--
-- MULTI AKCIÓK reads history using the Supabase publishable key only.
-- The TELEKI service_role key is NOT copied to the Vercel project.
